[package]
name = "repo-C"
version = "0.1.0"
edition = "2021"

[dependencies]
repo-A = { git = "https://github.com/rustlang-issue-14740/repo-A", branch = "main", features = ["sub"] }
repo-B = { git = "https://github.com/rustlang-issue-14740/repo-B", branch = "main" }
